package common;


import java.util.HashMap;
import java.util.Map;
import org.dmg.pmml.FieldName;

public class Test {
    public Test() {
    }

    public static void main(String[] args) {
        Map<FieldName, Object> paramsMap = new HashMap();
        paramsMap.put(new FieldName("ordhour"), 0);
        paramsMap.put(new FieldName("ordadvanceday"), 2);
        paramsMap.put(new FieldName("isoverflow_h"), 0);
        paramsMap.put(new FieldName("room_avg_orddate"), 542);
        paramsMap.put(new FieldName("remainder_saletime"), 67.38888889D);
        paramsMap.put(new FieldName("mhtl_nocancelroomnum_efdt_30d"), 3);
        paramsMap.put(new FieldName("mhtl_submitordnum_noroom_efdt_30d"), 0);
        paramsMap.put(new FieldName("mhtl_submitordnum_efdt_30d"), 3);
        paramsMap.put(new FieldName("mhtl_ordtime_median_efdt_30d"), 11.05D);
        paramsMap.put(new FieldName("htl_nocancelroomnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_noroom_efdt_30d"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("htl_ordtime_median_efdt_30d"), 452.6333333D);
        paramsMap.put(new FieldName("mbroom_submitordnum_noroom_efdt_30d"), 0);
        paramsMap.put(new FieldName("mbroom_submitordnum_efdt_30d"), 2);
        paramsMap.put(new FieldName("mbroom_nocancelroomnum_efdt_30d"), 2);
        paramsMap.put(new FieldName("broom_submitordnum_noroom_efdt_30d"), 0);
        paramsMap.put(new FieldName("broom_submitordnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("broom_nocancelroomnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("room_submitordnum_noroom_efdt_30d"), 0);
        paramsMap.put(new FieldName("room_submitordnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("room_nocancelroomnum_efdt_30d"), 0);
        paramsMap.put(new FieldName("roomrecommendlevel"), 2);
        paramsMap.put(new FieldName("mhtlroomquantity"), 158);
        paramsMap.put(new FieldName("mhtl_customereval"), 4.44958D);
        paramsMap.put(new FieldName("mhtl_maxroomnum_30d"), 18);
        paramsMap.put(new FieldName("htl_maxroomnum_30d"), -999);
        paramsMap.put(new FieldName("broom_maxroomnum_30d"), -999);
        paramsMap.put(new FieldName("room_maxroomnum_30d"), -999);
        paramsMap.put(new FieldName("mbroom_maxroomnum_30d"), 11);
        paramsMap.put(new FieldName("mhtl_maxroomnum_180d"), 28);
        paramsMap.put(new FieldName("htl_maxroomnum_180d"), -999);
        paramsMap.put(new FieldName("mbroom_maxroomnum_180d"), 26);
        paramsMap.put(new FieldName("room_maxroomnum_180d"), -999);
        paramsMap.put(new FieldName("mhtl_submitordnum_30d"), 160);
        paramsMap.put(new FieldName("mhtl_submitordnum_noroom_30d"), 0);
        paramsMap.put(new FieldName("mhtl_submitordnum_hold_30d"), 157);
        paramsMap.put(new FieldName("mhtl_submitordnum_hold_noroom_30d"), 0);
        paramsMap.put(new FieldName("mhtl_submitordnum_free_30d"), 3);
        paramsMap.put(new FieldName("mhtl_submitordnum_free_noroom_30d"), 0);
        paramsMap.put(new FieldName("mbroom_submitordnum_30d"), 90);
        paramsMap.put(new FieldName("mbroom_submitordnum_noroom_30d"), 0);
        paramsMap.put(new FieldName("mbroom_submitordnum_hold_30d"), 90);
        paramsMap.put(new FieldName("mbroom_submitordnum_hold_noroom_30d"), 0);
        paramsMap.put(new FieldName("mbroom_submitordnum_free_30d"), 0);
        paramsMap.put(new FieldName("mbroom_submitordnum_free_noroom_30d"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_30d"), -999);
        paramsMap.put(new FieldName("htl_submitordnum_noroom_30d"), -999);
        paramsMap.put(new FieldName("htl_submitordnum_hold_30d"), -999);
        paramsMap.put(new FieldName("htl_submitordnum_hold_noroom_30d"), -999);
        paramsMap.put(new FieldName("htl_submitordnum_free_30d"), -999);
        paramsMap.put(new FieldName("htl_submitordnum_free_noroom_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_noroom_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_hold_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_hold_noroom_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_free_30d"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_free_noroom_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_noroom_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_hold_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_hold_noroom_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_free_30d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_free_noroom_30d"), -999);
        paramsMap.put(new FieldName("group_submitordnum_30d"), -999);
        paramsMap.put(new FieldName("group_submitordnum_noroom_30d"), -999);
        paramsMap.put(new FieldName("supplier_submitordnum_30d"), 508);
        paramsMap.put(new FieldName("supplier_submitordnum_noroom_30d"), 0);
        paramsMap.put(new FieldName("supplier_ordtime_median_efdt_30d"), 2.5D);
        paramsMap.put(new FieldName("room_submitordnum_14d"), -999);
        paramsMap.put(new FieldName("room_submitordnum_noroom_14d"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_14d"), 55);
        paramsMap.put(new FieldName("mbroom_submitordnum_noroom_14d"), 0);
        paramsMap.put(new FieldName("cityi"), 0.13931029D);
        paramsMap.put(new FieldName("cityi_diff"), 9.1438E-4D);
        paramsMap.put(new FieldName("zonei"), 0.13623674D);
        paramsMap.put(new FieldName("zonei_diff"), 0.002093807D);
        paramsMap.put(new FieldName("zonestari"), 0.16207951D);
        paramsMap.put(new FieldName("zonestari_diff"), 0);
        paramsMap.put(new FieldName("highestdegree"), -999);
        paramsMap.put(new FieldName("lowestdegree"), -999);
        paramsMap.put(new FieldName("roomclass_contractrooms_efdt"), -999);
        paramsMap.put(new FieldName("holiday_ord"), 0);
        paramsMap.put(new FieldName("day_of_holiday_ord"), 0);
        paramsMap.put(new FieldName("mhtl_submitordnum_efdt_30d_mfratio"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_efdt_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_efdt_30d_mfratio"), 0);
        paramsMap.put(new FieldName("broom_submitordnum_efdt_30d_mfratio"), -999);
        paramsMap.put(new FieldName("room_submitordnum_efdt_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mhtl_submitordnum_30d_mfratio"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_30d_mfratio"), 0);
        paramsMap.put(new FieldName("broom_submitordnum_30d_mfratio"), -999);
        paramsMap.put(new FieldName("room_submitordnum_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mhtl_submitordnum_hold_30d_mfratio"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_hold_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_hold_30d_mfratio"), 0);
        paramsMap.put(new FieldName("broom_submitordnum_hold_30d_mfratio"), -999);
        paramsMap.put(new FieldName("room_submitordnum_hold_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mhtl_submitordnum_free_30d_mfratio"), 0);
        paramsMap.put(new FieldName("htl_submitordnum_free_30d_mfratio"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_free_30d_mfratio"), -999);
        paramsMap.put(new FieldName("broom_submitordnum_free_30d_mfratio"), -999);
        paramsMap.put(new FieldName("room_submitordnum_free_30d_mfratio"), -999);
        paramsMap.put(new FieldName("group_submitordnum_30d_mfratio"), -999);
        paramsMap.put(new FieldName("supplier_submitordnum_30d_mfratio"), 0);
        paramsMap.put(new FieldName("room_submitordnum_14d_mfratio"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_14d_mfratio"), 0);
        paramsMap.put(new FieldName("mhtl_submitordnum_efdt_30d_mfratio_compare"), -0.001266154D);
        paramsMap.put(new FieldName("htl_submitordnum_efdt_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_efdt_30d_mfratio_compare"), -0.001013757D);
        paramsMap.put(new FieldName("broom_submitordnum_efdt_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("room_submitordnum_efdt_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("mhtl_submitordnum_30d_mfratio_compare"), -0.002918646D);
        paramsMap.put(new FieldName("htl_submitordnum_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_30d_mfratio_compare"), -0.002753233D);
        paramsMap.put(new FieldName("broom_submitordnum_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("room_submitordnum_30d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("room_submitordnum_14d_mfratio_compare"), -999);
        paramsMap.put(new FieldName("mbroom_submitordnum_14d_mfratio_compare"), -0.002744489D);
        paramsMap.put(new FieldName("room_avg_orddate_compare"), 1);
        paramsMap.put(new FieldName("degree"), 0);
        paramsMap.put(new FieldName("weather"), 0);
        paramsMap.put(new FieldName("timeperiod_1"), 1);
        paramsMap.put(new FieldName("timeperiod_2"), 0);
        paramsMap.put(new FieldName("timeperiod_3"), 0);
        paramsMap.put(new FieldName("isstraightconnect_0"), 1);
        paramsMap.put(new FieldName("isstraightconnect_1"), 0);
        paramsMap.put(new FieldName("star_0"), 0);
        paramsMap.put(new FieldName("star_2"), 0);
        paramsMap.put(new FieldName("star_3"), 0);
        paramsMap.put(new FieldName("star_4"), 1);
        paramsMap.put(new FieldName("star_5"), 0);
        paramsMap.put(new FieldName("cprflag_0"), 1);
        paramsMap.put(new FieldName("cprflag_1"), 0);
        paramsMap.put(new FieldName("cprflag_2"), 0);
        paramsMap.put(new FieldName("cprflag_3"), 0);
        paramsMap.put(new FieldName("cprflag_4"), 0);
        paramsMap.put(new FieldName("is_belong_group_0"), 1);
        paramsMap.put(new FieldName("is_belong_group_1"), 0);
        ModelInvoker invoker = new ModelInvoker("PredFalseHoldRoom.pmml");
        Map<FieldName, ?> scoreMap = invoker.invoke(paramsMap);
        System.out.println(scoreMap.get(new FieldName("probability_0")));
        System.out.println(scoreMap.get(new FieldName("probability_1")));
    }
}
